---
- name: Configure mariadb
  ansible.builtin.import_tasks: config.yml

- name: Check mariadb containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Import tasks from recover_cluster.yml
  ansible.builtin.import_tasks: recover_cluster.yml
  vars:
    mariadb_cluster_exists: true
  when: migration_flag is defined

- name: Bootstrap mariadb service
  ansible.builtin.import_tasks: bootstrap.yml
