---
- name: Group MariaDB hosts based on shards
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: "{{ hostvars[item]['mariadb_shard_group'] }}"
  loop: "{{ groups['mariadb'] }}"
  changed_when: false

- name: "Include tasks for action {{ kolla_action }}"
  ansible.builtin.include_tasks: "{{ kolla_action }}.yml"
