---
- name: Set wsrep_sst_method to rsync for upgrade
  become: true
  changed_when: true
  no_log: true
  ansible.builtin.shell: >
    {{ kolla_container_engine }} exec {{ mariadb_service.container_name }}
    mariadb -uroot -p{{ database_password }}
    -e "SET GLOBAL wsrep_sst_method='rsync';"

- name: Import tasks from deploy.yml
  ansible.builtin.import_tasks: deploy.yml
  vars:
    mariadb_wsrep_sst_method: "rsync"

- name: Set wsrep_sst_method to mariabackup after upgrade
  become: true
  changed_when: true
  no_log: true
  ansible.builtin.shell: >
    {{ kolla_container_engine }} exec {{ mariadb_service.container_name }}
    mariadb -uroot -p{{ database_password }}
    -e "SET GLOBAL wsrep_sst_method='mariabackup';"

- name: Import tasks from deploy.yml
  ansible.builtin.import_tasks: deploy.yml
