---
other:
  - |
    This release exposes additional configuration options for OpenStack
    Compute consoles which utilize the SPICE protocol. These configuration
    options have been defaulted to the previous implied values, so do not
    need to be set if you're happy with the current behavior. The
    Kolla-Ansible Nova guide has been updated with further details of these
    new configuration options.
