---
features:
  - |
    New variables ``rabbitmq_stream_max_segment_size_bytes`` and
    ``rabbitmq_stream_segment_max_age`` are added to make RabbitMQ stream
    retention policy configurable.
    These two new variables are only applied when
    ``om_enable_rabbitmq_stream_fanout`` is set to true.
    It is recommended to tune the values based on user's environment to
    prevent leaving too many ready messages in stream queues.
