---
- name: Configure trove
  ansible.builtin.import_tasks: config.yml

- name: Check trove containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run trove bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
