---
- name: Configure letsencrypt
  ansible.builtin.import_tasks: config.yml

- name: Check letsencrypt containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
