---
- name: Import tasks from validate_docker_execute.yml
  ansible.builtin.import_tasks: validate_docker_execute.yml

- name: Import tasks from prune_images.yml
  ansible.builtin.import_tasks: prune_images.yml
