---
# TODO(mnasiadka): Remove after 2027.1
- name: Remove keystone.cfg from haproxy
  become: true
  ansible.builtin.file:
    path: "{{ node_config_directory }}/haproxy/services.d/keystone.cfg"
    state: absent

- name: "Configure loadbalancer for {{ project_name }}"
  ansible.builtin.import_role:
    name: loadbalancer-config
  vars:
    project_services: "{{ keystone_services }}"
  tags: always
