---
- name: List configured attribute mappings (that can be used by IdPs)
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.federation_mapping_info
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
  run_once: true
  register: existing_mappings

- name: Remove unmanaged attribute mappings
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.federation_mapping
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
      name: "{{ item.name }}"
      state: absent
  run_once: true
  with_items: "{{ existing_mappings.mappings }}"
  when:
    - item.name not in (keystone_identity_mappings | map(attribute='name') | list)
    - keystone_should_remove_attribute_mappings

- name: Create unexisting domains
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: "openstack.cloud.identity_domain"
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
      name: "{{ item.openstack_domain }}"
      state: present
  run_once: true
  with_items: "{{ keystone_identity_providers }}"

- name: Register attribute mappings in OpenStack
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.federation_mapping
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
      name: "{{ item.name }}"
      rules: "{{ '{{ keystone_identity_mapping_rules | from_json }}' }}"
      state: present
    module_extra_vars:
      keystone_identity_mapping_rules: "{{ lookup('ansible.builtin.file', item.file) }}"
  run_once: true
  with_items: "{{ keystone_identity_mappings }}"

- name: List configured IdPs
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.federation_idp_info
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
  run_once: true
  register: existing_idps

- name: Remove unmanaged identity providers
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.federation_idp
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
      name: "{{ item.name }}"
      state: absent
  run_once: true
  with_items: "{{ existing_idps.identity_providers }}"
  when:
    - item.name not in (keystone_identity_providers | map(attribute='name') | list)
    - keystone_should_remove_identity_providers

- name: Gather Identity Domains information
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.identity_domain_info
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
  run_once: true
  register: existing_identity_domains

- name: Verify that required Identity Domains exist
  ansible.builtin.fail:
    msg: >
      Domain "{{ item.openstack_domain }}" was not found in OpenStack.
      Please create it first or check your keystone_identity_providers configuration.
  run_once: true
  loop: "{{ keystone_identity_providers }}"
  when: >
    existing_identity_domains.domains |
    selectattr('name', 'equalto', item.openstack_domain) |
    list | length == 0

- name: Register Identity Providers in OpenStack
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.federation_idp
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
      description: "{{ item.public_name }}"
      remote_ids: "{{ '{{ keystone_identity_provider_remote_ids | from_json }}' }}"
      domain_id: "{{ existing_identity_domains.domains | selectattr('name', 'equalto', item.openstack_domain) | map(attribute='id') | first }}"
      name: "{{ item.name }}"
      is_enabled: true
      state: present
    module_extra_vars:
      keystone_identity_provider_remote_ids: "{{ [item.identifier] | to_json }}"
  run_once: true
  with_items: "{{ keystone_identity_providers }}"

- name: Configure attribute mappings for each Identity Provider. (We expect the mappings to be configured by the operator)
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.keystone_federation_protocol
    module_args:
      auth: "{{ openstack_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      region_name: "{{ openstack_region_name }}"
      interface: "{{ openstack_interface }}"
      ca_cert: "{{ openstack_cacert if openstack_cacert != '' else omit }}"
      idp: "{{ item.name }}"
      mapping: "{{ item.attribute_mapping }}"
      name: "{{ item.protocol }}"
      state: present
  run_once: true
  with_items: "{{ keystone_identity_providers }}"
