---
- name: Creating admin project, user, role, service, and endpoint
  become: true
  ansible.builtin.command: >
    {{ kolla_container_engine }} exec keystone kolla_keystone_bootstrap
    {{ keystone_admin_user }} {{ keystone_admin_password }} {{ keystone_admin_project }}
    admin {{ keystone_internal_url }} {{ keystone_public_url }} {{ region }}
  register: keystone_bootstrap
  changed_when: (keystone_bootstrap.stdout | from_json).changed
  failed_when: (keystone_bootstrap.stdout | from_json).failed
  run_once: true
  loop: "{{ multiple_regions_names }}"
  loop_control:
    loop_var: region

- name: Register keystone service, endpoints, and users in Keystone
  ansible.builtin.import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_keystone_auth }}"
    service_ks_register_services: "{{ keystone_ks_services }}"
  run_once: true

- name: Creating default user role
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: openstack.cloud.identity_role
    module_args:
      name: "{{ keystone_default_user_role }}"
      auth: "{{ openstack_keystone_auth }}"
      cloud: "{{ openstack_auth_cloud }}"
      endpoint_type: "{{ openstack_interface }}"
      cacert: "{{ openstack_cacert }}"
      region_name: "{{ openstack_region_name }}"
  run_once: true
