---
- name: Import tasks from config-host.yml
  ansible.builtin.import_tasks: config-host.yml

- name: Import tasks from config.yml
  ansible.builtin.import_tasks: config.yml

- name: Import tasks from check-containers.yml
  ansible.builtin.import_tasks: check-containers.yml

- name: Include tasks from config-neutron-fake.yml
  ansible.builtin.include_tasks: config-neutron-fake.yml
  when:
    - inventory_hostname in groups['compute']
    - enable_nova_fake | bool

- name: Import tasks from bootstrap_service.yml
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
