---
- name: Import tasks from neutron_plugin_agent_check.yml
  ansible.builtin.import_tasks: neutron_plugin_agent_check.yml

- name: Include tasks from rolling_upgrade.yml
  ansible.builtin.include_tasks: rolling_upgrade.yml
  when: neutron_enable_rolling_upgrade | bool

- name: Include tasks from legacy_upgrade.yml
  ansible.builtin.include_tasks: legacy_upgrade.yml
  when: not neutron_enable_rolling_upgrade | bool
