#!/bin/bash
if [[ -f kolla-sample-vnffgd.yaml ]]; then
    echo "Deleting VNFFG"
    openstack vnf graph delete kolla-sample-vnffg
    echo "Deleting VNFFGD"
    openstack vnf graph descriptor delete kolla-sample-vnffgd
    echo "Deleting sample sfc instances"
    openstack server delete kolla_sfc_server kolla_sfc_client
fi
echo "Deleting sample VNF"
openstack vnf delete kolla-sample-vnf
while openstack vnf list | grep -q kolla-sample-vnf; do
    sleep 1
done
echo "Deleting sample VNFD"
openstack vnf descriptor delete kolla-sample-vnfd
echo "Deleting sample VIM"
openstack vim delete kolla-sample-vim
echo "Removing sample config"
rm -rf ./kolla-sample-*
