---
- name: Test for leaked passwords in journal
  become: true
  kolla_ansible_password_check:
    passwords_file: "{{ kolla_ansible_check_passwords_file }}"
    ignore_keys: "{{ kolla_ansible_check_ignore_keys }}"
  when: inventory_hostname == 'primary'
