---
- name: Register nova in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure nova
  ansible.builtin.import_tasks: config.yml

- name: Check nova containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
