---
- name: Register kuryr in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure kuryr
  ansible.builtin.import_tasks: config.yml

- name: Check kuryr containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone kuryr repository
  ansible.builtin.include_tasks: clone.yml
  when:
    - kuryr_dev_mode | bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
