---
- name: Configure cron
  ansible.builtin.import_tasks: config.yml

- name: Check cron containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Bootstrap cron service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
