---
- name: Register ceilometer in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure ceilometer
  ansible.builtin.import_tasks: config.yml

- name: Check ceilometer containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone ceilometer repository
  ansible.builtin.include_tasks: clone.yml
  when: ceilometer_dev_mode | bool

- name: Bootstrap ceilometer service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
