---
- name: Configure ceilometer
  ansible.builtin.import_tasks: config.yml

- name: Check ceilometer containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run ceilometer bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
