---
- name: Configure grafana
  ansible.builtin.import_tasks: config.yml

- name: Check grafana containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Bootstrap grafana service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Import tasks from post_config.yml
  ansible.builtin.import_tasks: post_config.yml
