---
- name: Import tasks from config-host.yml
  ansible.builtin.import_tasks: config-host.yml

- name: Configure openvswitch
  ansible.builtin.import_tasks: config.yml

- name: Check openvswitch containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Import tasks from post-config.yml
  ansible.builtin.import_tasks: post-config.yml
