---
- name: Register watcher in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure watcher
  ansible.builtin.import_tasks: config.yml

- name: Check watcher containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone watcher repository
  ansible.builtin.include_tasks: clone.yml
  when: watcher_dev_mode | bool

- name: Bootstrap watcher service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
