---
- name: Configure watcher
  ansible.builtin.import_tasks: config.yml

- name: Check watcher containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run watcher bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
