---
- name: Register magnum in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure magnum
  ansible.builtin.import_tasks: config.yml

- name: Check magnum containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone magnum repository
  ansible.builtin.include_tasks: clone.yml
  when: magnum_dev_mode | bool

- name: Bootstrap magnum service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
