---
- name: Register aodh in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure aodh
  ansible.builtin.import_tasks: config.yml

- name: Check aodh containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone aodh repository
  ansible.builtin.include_tasks: clone.yml
  when: aodh_dev_mode | bool

- name: Bootstrap aodh service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
