---
- name: Register cinder in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure cinder
  ansible.builtin.import_tasks: config.yml

- name: Check cinder containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone cinder repository
  ansible.builtin.include_tasks: clone.yml
  when: cinder_dev_mode | bool

- name: Bootstrap cinder service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
