---
- name: Configure cloudkitty
  ansible.builtin.import_tasks: config.yml

- name: Check cloudkitty containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run cloudkitty bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
