---
- name: Register barbican in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure barbican
  ansible.builtin.import_tasks: config.yml

- name: Check barbican containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone barbican repository
  ansible.builtin.include_tasks: clone.yml
  when: barbican_dev_mode | bool

- name: Bootstrap barbican service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
