---
- name: Configure gnocchi
  ansible.builtin.import_tasks: config.yml

- name: Check gnocchi containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run gnocchi bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
