---
- name: Configure ovs-dpdk
  ansible.builtin.import_tasks: config.yml

- name: Check ovs-dpdk containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
