---
- name: Configure ovn-controller
  ansible.builtin.import_tasks: config.yml

- name: Check ovn-controller containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Import tasks from setup-ovs.yml
  ansible.builtin.import_tasks: setup-ovs.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
