---
- name: Clone manila repository
  ansible.builtin.include_tasks: clone.yml
  when: manila_dev_mode | bool

- name: Register manila in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure manila
  ansible.builtin.import_tasks: config.yml

- name: Check manila containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Bootstrap manila service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
