---
- name: Register blazar in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure blazar
  ansible.builtin.import_tasks: config.yml

- name: Check blazar containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone blazar repository
  ansible.builtin.include_tasks: clone.yml
  when: blazar_dev_mode | bool

- name: Bootstrap blazar service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
