---
- name: Configure blazar
  ansible.builtin.import_tasks: config.yml

- name: Check blazar containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run blazar bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
