---
kolla_ansible_check_passwords_file: /etc/kolla/passwords.yml
kolla_ansible_check_ignore_keys:
  # TODO(mnasiadka): Fix in ansible/roles/mariadb/tasks/bootstrap_cluster.yml#L14
  - database_password
  # TODO(mnasiadka): Fix in ansible/roles/heat/tasks/bootstrap_service.yml#L22
  - heat_domain_admin_password
  # TODO(mnasiadka): Fix openstack_auth all over the place in kolla_toolbox module_args
  - keystone_admin_password
  # TODO(mnasiadka): Fix in ansible/roles/nova/tasks/map_cell0.yml#L12
  - nova_database_password
  # TODO(mnasiadka): Fix in ansible/roles/octavia-certificates/tasks/server_ca.yml
  - octavia_ca_password
  # TODO(mnasiadka): Fix in ansible/roles/octavia-certificates/tasks/server_ca.yml
  - octavia_client_ca_password
  # TODO(mnasiadka): Fix openstack_auth all over the place in kolla_toolbox module_args
  - octavia_keystone_password
  # TODO(mnasiadka): Fix in ansible/roles/valkey/tasks/check.yml#L10
  - valkey_master_password
  # TODO(mnasiadka) Fix in ansible/roles/grafana/tasks/post_config.yml#L24
  - prometheus_alertmanager_password
  # TODO(mnasiadka) Fix in ansible/roles/rabbitmq/defaults/main.yml#L11
  - rabbitmq_cluster_cookie
