---
- name: Register tacker in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure tacker
  ansible.builtin.import_tasks: config.yml

- name: Check tacker containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone tacker repository
  ansible.builtin.include_tasks: clone.yml
  when:
    - tacker_dev_mode | bool

- name: Bootstrap tacker service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
