---
# MariaDB setup
test_database_port: 3306
test_database_user: "root_shard_0"
test_database_tls_enabled: false
test_database_vip: "{{ undef() }}" # required
test_database_password: "{{ undef() }}"
test_expected_mariadb_host_number: 3
# ProxySQL setup
test_proxysql_port: 6032
test_proxysql_user: "kolla-admin"
test_proxysql_password: "{{ undef() }}"
