---
- name: Configure prometheus
  ansible.builtin.import_tasks: config.yml

- name: Check prometheus containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Bootstrap prometheus service
  ansible.builtin.include_tasks: bootstrap.yml
  when: inventory_hostname in groups['prometheus-mysqld-exporter']

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
