---
# NOTE(yoctozepto): This is kolla-ansible-tenks-venv to avoid a conflict with
# the venv that Tenks creates by itself by default to ~/tenks-venv
deploy_tenks_venv_path: "{{ ansible_env.HOME }}/kolla-ansible-tenks-venv"
deploy_tenks_src_path: "{{ ansible_env.HOME ~ '/' ~ zuul.projects['opendev.org/openstack/tenks'].src_dir }}"
