---
- name: Reset RabbitMQ state
  hosts: rabbitmq
  tasks:
    - name: Include RabbitMQ reset-state tasks
      ansible.builtin.include_role:
        name: rabbitmq
        tasks_from: reset-state
      when:
        - enable_rabbitmq | bool
