---
- name: Register zun in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure zun
  ansible.builtin.import_tasks: config.yml

- name: Check zun containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone zun repository
  ansible.builtin.include_tasks: clone.yml
  when: zun_dev_mode | bool

- name: Bootstrap zun service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
