---
- name: Copying over ceph.conf for Zun
  ansible.builtin.copy:
    src: "{{ node_custom_config }}/zun/zun-compute/{{ ceph_cluster }}.conf"
    dest: "{{ node_config_directory }}/zun-compute/"
    mode: "0660"
  become: true

- name: Copy over Ceph keyring files for zun-compute
  ansible.builtin.copy:
    src: "{{ node_custom_config }}/zun/zun-compute/{{ ceph_cluster }}.client.{{ ceph_cinder_user }}.keyring"
    dest: "{{ node_config_directory }}/zun-compute/"
    mode: "0660"
  become: true
  when: external_ceph_cephx_enabled | bool

- name: Ensuring config directory has correct owner and permission
  become: true
  ansible.builtin.file:
    path: "{{ node_config_directory }}/zun-compute"
    recurse: true
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
