---
- name: Configure zun
  ansible.builtin.import_tasks: config.yml

- name: Check zun containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run zun bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
