#!/bin/bash

echo "Deleting cluster"
magnum cluster-delete testcluster
while magnum cluster-list | grep -q testcluster; do
    sleep 1
done
echo "Deleting cluster-template"
magnum cluster-template-delete testclustertemplate
