---
- name: Configure skyline
  ansible.builtin.import_tasks: config.yml

- name: Check skyline containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
