#!/bin/bash
#
# This script is meant to be run once after running start for the first
# time.  This script do a cirros image and registers it.  Then it
# configures networking and nova quotas to allow 40 m1.small instances
# to be created.

ARCH=$(uname -m)
IMAGE_PATH=/opt/cache/files/
IMAGE_URL=http://download.cirros-cloud.net/0.4.0/
IMAGE=cirros-0.4.0-${ARCH}-disk.img
IMAGE_NAME=cirros
IMAGE_TYPE=linux

source $(dirname "$0")/init-runonce.config

# Sanity Check
[[ -z "$" ]] && echo " undefined"  && exit -1
[[ -z "$" ]] && echo " undefined"  && exit -1
[[ -z "$" ]] && echo " undefined"  && exit -1
[[ -z "$" ]] && echo " undefined"  && exit -1
[[ -z "$" ]] && echo " undefined"  && exit -1

[[ -z "$EXT_PHYSNET_NAME" ]] && echo "EXT_PHYSNET_NAME undefined"  && exit -1
[[ -z "$EXT_NET_NAME" ]] && echo "EXT_NET_NAME undefined"  && exit -1
[[ -z "$EXT_NET_SUBNET" ]] && echo "EXT_NET_SUBNET undefined"  && exit -1
[[ -z "$EXT_NET_CIDR" ]] && echo "EXT_NET_CIDR undefined"  && exit -1
[[ -z "$EXT_NET_RANGE" ]] && echo "EXT_NET_RANGE undefined"  && exit -1
[[ -z "$EXT_NET_GATEWAY" ]] && echo "EXT_NET_GATEWAY undefined"  && exit -1

[[ -z "$PRIV_NET_NAME" ]] && echo "PRIV_NET_NAME undefined"  && exit -1
[[ -z "$PRIV_NET_SUBNET" ]] && echo "PRIV_NET_SUBNET undefined"  && exit -1
[[ -z "$PRIV_NET_ROUTER" ]] && echo "PRIV_NET_ROUTER undefined"  && exit -1
[[ -z "$PRIV_NET_CIDR" ]] && echo "PRIV_NET_CIDR undefined"  && exit -1
[[ -z "$PRIV_NET_GATEWAY" ]] && echo "PRIV_NET_GATEWAY undefined"  && exit -1

[[ -z "$SSH_KEY_NAME" ]] && echo "SSH_KEY_NAME undefined"  && exit -1

# Sanitize language settings to avoid commands bailing out
# with "unsupported locale setting" errors.
unset LANG
unset LANGUAGE
LC_ALL=C
export LC_ALL
for i in curl openstack; do
    if [[ ! $(type ${i} 2>/dev/null) ]]; then
        if [ "${i}" == 'curl' ]; then
            echo "Please install ${i} before proceeding"
        else
            echo "Please install python-${i}client before proceeding"
        fi
        exit
    fi
done

# Test for credentials set
if [[ "${OS_USERNAME}" == "" ]]; then
    echo "No Keystone credentials specified.  Try running source openrc"
    exit
fi

# Test to ensure configure script is run only once
if openstack image list | grep -q cirros; then
    echo "This tool should only be run once per deployment."
    exit
fi

echo Checking for locally available cirros image.
# Let's first try to see if the image is available locally
# nodepool nodes caches them in $IMAGE_PATH
if ! [ -f "${IMAGE_PATH}/${IMAGE}" ]; then
    IMAGE_PATH='./'
    if ! [ -f "${IMAGE_PATH}/${IMAGE}" ]; then
        echo None found, downloading cirros image.
        curl -L -o ${IMAGE_PATH}/${IMAGE} ${IMAGE_URL}/${IMAGE}
    fi
else
    echo Using cached cirros image from the nodepool node.
fi

EXTRA_PROPERTIES=
if [ ${ARCH} == aarch64 ]; then
    EXTRA_PROPERTIES="--property hw_firmware_type=uefi"
fi

echo Creating glance image.
openstack image create --disk-format qcow2 --container-format bare --public \
    --property os_type=${IMAGE_TYPE} ${EXTRA_PROPERTIES} --file ${IMAGE_PATH}/${IMAGE} ${IMAGE_NAME}

echo Configuring neutron.
openstack network create --external --provider-physical-network ${EXT_PHYSNET_NAME} \
    --provider-network-type flat ${EXT_NET_NAME}
openstack subnet create --no-dhcp \
    --allocation-pool ${EXT_NET_RANGE} --network ${EXT_NET_NAME} \
    --subnet-range ${EXT_NET_CIDR} --gateway ${EXT_NET_GATEWAY} ${EXT_NET_SUBNET}

openstack network create --provider-network-type vxlan ${PRIV_NET_NAME}
openstack subnet create --subnet-range ${PRIV_NET_CIDR} --network ${PRIV_NET_NAME} \
    --gateway ${PRIV_NET_GATEWAY} --dns-nameserver 8.8.8.8 ${PRIV_NET_SUBNET}

openstack router create ${PRIV_NET_ROUTER}
openstack router add subnet demo-router ${PRIV_NET_SUBNET}
openstack router set --external-gateway ${EXT_NET_NAME} ${PRIV_NET_ROUTER}

# Get admin user and tenant IDs
ADMIN_USER_ID=$(openstack user list | awk '/ admin / {print $2}')
ADMIN_PROJECT_ID=$(openstack project list | awk '/ admin / {print $2}')
ADMIN_SEC_GROUP=$(openstack security group list --project ${ADMIN_PROJECT_ID} | awk '/ default / {print $2}')

# Sec Group Config
openstack security group rule create --ingress --ethertype IPv4 \
    --protocol icmp ${ADMIN_SEC_GROUP}
openstack security group rule create --ingress --ethertype IPv4 \
    --protocol tcp --dst-port 22 ${ADMIN_SEC_GROUP}
# Open heat-cfn so it can run on a different host
openstack security group rule create --ingress --ethertype IPv4 \
    --protocol tcp --dst-port 8000 ${ADMIN_SEC_GROUP}
openstack security group rule create --ingress --ethertype IPv4 \
    --protocol tcp --dst-port 8080 ${ADMIN_SEC_GROUP}

if [ ! -f ~/.ssh/id_rsa.pub ]; then
    echo Generating ssh key.
    ssh-keygen -t rsa -f ~/.ssh/id_rsa
fi
if [ -r ~/.ssh/id_rsa.pub ]; then
    echo Configuring nova public key and quotas.
    openstack keypair create --public-key ~/.ssh/id_rsa.pub ${SSH_KEY_NAME}
fi

# Increase the quota to allow 40 m1.small instances to be created

# 40 instances
openstack quota set --instances 40 ${ADMIN_PROJECT_ID}

# 40 cores
openstack quota set --cores 40 ${ADMIN_PROJECT_ID}

# 96GB ram
openstack quota set --ram 96000 ${ADMIN_PROJECT_ID}

# add default flavors, if they don't already exist
if ! openstack flavor list | grep -q m1.tiny; then
    openstack flavor create --id 1 --ram 512 --disk 1 --vcpus 1 m1.tiny
    openstack flavor create --id 2 --ram 2048 --disk 20 --vcpus 1 m1.small
    openstack flavor create --id 3 --ram 4096 --disk 40 --vcpus 2 m1.medium
    openstack flavor create --id 4 --ram 8192 --disk 80 --vcpus 4 m1.large
    openstack flavor create --id 5 --ram 16384 --disk 160 --vcpus 8 m1.xlarge
fi

cat << EOF

Done.

To deploy a demo instance, run:

openstack server create \\
    --image ${IMAGE_NAME} \\
    --flavor m1.tiny \\
    --key-name mykey \\
    --network ${PRIV_NET_NAME} \\
    demo1
EOF
