---
- name: Configure bifrost
  ansible.builtin.import_tasks: config.yml

- name: Start bifrost containers
  ansible.builtin.import_tasks: start.yml

- name: Bootstrap bifrost service
  ansible.builtin.import_tasks: bootstrap.yml
