---
ovn_vpnaas_openrc: "/etc/kolla/admin-openrc.sh"
ovn_vpnaas_venv: "{{ ansible_env.HOME }}/openstackclient-venv"

ovn_vpnaas_activate: ". {{ ovn_vpnaas_venv }}/bin/activate &&"

ovn_vpnaas_west_cidr: "192.168.10.0/24"
ovn_vpnaas_east_cidr: "192.168.20.0/24"
ovn_vpnaas_psk: "secret"

ovn_vpnaas_consistency_retries: 10
ovn_vpnaas_consistency_delay: 5
ovn_vpnaas_tunnel_retries: 20
ovn_vpnaas_tunnel_delay: 15
