---
- name: Register mistral in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure mistral
  ansible.builtin.import_tasks: config.yml

- name: Check mistral containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone mistral repository
  ansible.builtin.include_tasks: clone.yml
  when: mistral_dev_mode | bool

- name: Bootstrap mistral service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
