---
- name: Configure mistral
  ansible.builtin.import_tasks: config.yml

- name: Check mistral containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run mistral bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
