---
- name: Register designate in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure designate
  ansible.builtin.import_tasks: config.yml

- name: Check designate containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Clone designate repository
  ansible.builtin.include_tasks: clone.yml
  when: designate_dev_mode | bool

- name: Bootstrap designate service
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Import tasks from update_pools.yml
  ansible.builtin.import_tasks: update_pools.yml
