---
- name: Configure designate
  ansible.builtin.import_tasks: config.yml

- name: Check designate containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Run designate bootstrap container
  ansible.builtin.import_tasks: bootstrap_service.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Import tasks from update_pools.yml
  ansible.builtin.import_tasks: update_pools.yml
